Repository rilling/OpenTracksConcordia, pull requests merged in 2023-11, with the labels that each got.

#123 Fix: variable shadowing issue solved
  build.gradle
  my-release-key.keystore
  src/main/java/de/dennisguse/opentracks/services/TrackDeleteService.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java
Labels: Technical Debt, Group 5

#238 Time of day announcement feature #178
  src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
  src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
  src/main/java/de/dennisguse/opentracks/util/CTime.java
  src/main/java/de/dennisguse/opentracks/util/SpeechTxtForTime.java
  src/main/res/values/settings.xml
  src/main/res/values/strings.xml
  src/main/res/xml/settings_announcements.xml
Labels: enhancement, Group 2

#276 Group4 motivation
  src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncement.java
  src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementManager.java
  src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
  src/main/java/de/dennisguse/opentracks/util/MotivationalAnnouncements.java
Labels: enhancement, Group 4

#138 Added missing @deprecated javadoc tag
  src/main/java/de/dennisguse/opentracks/chart/ChartPoint.java
Labels: Technical Debt, Group 4

#280 Feature: User Profile
  src/main/java/de/dennisguse/opentracks/settings/MainSettingsFragment.java
  src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
  src/main/java/de/dennisguse/opentracks/settings/UserProfileSettingsFragment.java
  src/main/res/drawable/user_profile.xml
  src/main/res/values/settings.xml
  src/main/res/values/strings.xml
  src/main/res/xml/settings.xml
  src/main/res/xml/settings_user_profile.xml
Labels: enhancement, Group 9

#302 Feature: Weather info
  src/main/java/de/dennisguse/opentracks/data/models/WeatherInfo.java
  src/main/java/de/dennisguse/opentracks/services/WeatherFetchService.java
Labels: enhancement, Group 1

#198 Added resume and finish button in pause mode
  src/main/java/de/dennisguse/opentracks/TrackListActivity.java
  src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
  src/main/res/layout/track_list.xml
  src/main/res/layout/track_recording.xml
  src/main/res/layout/track_stopped.xml
  src/main/res/values/strings.xml
Labels: enhancement, Group 6

#295 Calculate calories based on Basal Metabolic Rate
  src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
Labels: Group 10
