Repository rilling/OpenTracksConcordia, pull requests merged in 2023-10, with the labels that each got.

#23 Add a private constructor to hide the implicit public one
  src/main/java/de/dennisguse/opentracks/viewmodels/Mapping.java
Labels: Technical Debt, Group 10

#105 Change constructor visibility in SpeedOrPace class
  src/main/java/de/dennisguse/opentracks/viewmodels/GenericStatisticsViewHolder.java
Labels: Group 10

#107 Nisha bhatia
  src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
  src/main/java/de/dennisguse/opentracks/share/DescriptionGenerator.java
  src/main/java/de/dennisguse/opentracks/share/ShareUtils.java
  src/main/java/de/dennisguse/opentracks/util/PermissionRequester.java
Labels: Technical Debt, Group 8

#93 Removed the deprecated use of setTextAppearance #92
  src/main/java/de/dennisguse/opentracks/viewmodels/SensorStatisticsViewHolder.java
Labels: Technical Debt, Group 8

#124 Remove this use of "setTextAppearance"; it is deprecated.
  src/main/java/de/dennisguse/opentracks/viewmodels/GenericStatisticsViewHolder.java
Labels: Group 10

#135 Fix Technical Debt: Eliminate Deprecated setTextAppearance Method Usage
  src/main/java/de/dennisguse/opentracks/viewmodels/ClockViewHolder.java
Labels: Group 10

#141 Merge this if statement with the enclosing one
  src/main/java/de/dennisguse/opentracks/ui/util/ScrollVisibleViews.java
Labels: Technical Debt, Group 2

#151 Group 02 sourav
  src/main/java/de/dennisguse/opentracks/ui/util/RecyclerViewSwipeDeleteCallback.java
  src/main/java/de/dennisguse/opentracks/ui/util/ScrollVisibleViews.java
Labels: Technical Debt, Group 2

#32 Fixed unused tag variable
  src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java
Labels: Group 9

#108 Fix variable case
  src/main/java/de/dennisguse/opentracks/publicapi/AbstractAPIActivity.java
Labels: Technical Debt, Group 9

#163 Remove this unused "track" local variable
  build.gradle
  gradle.properties
  src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
Labels: Technical Debt, Group 9

#145 Removed extra parenthesis
  src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
Labels: Technical Debt, Group 7

#58 Rename this constant name to match the regular expression '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.
  src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
Labels: Technical Debt, Group 7

#76 fix: merged two if statements with one
  src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
  src/main/java/de/dennisguse/opentracks/io/file/importer/ImportActivity.java
Labels: Group 7

#156 Rename this constant name to match the regular expression '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.
  src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
Labels: Technical Debt, Group 7

#139 Delivery 1
  src/main/java/de/dennisguse/opentracks/settings/ActivityTypePreference.java
  src/main/java/de/dennisguse/opentracks/settings/ImportExportSettingsFragment.java
  src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
  src/main/java/de/dennisguse/opentracks/settings/SensorsSettingsFragment.java
  src/main/java/de/dennisguse/opentracks/settings/UserInterfaceSettingsFragment.java
Labels: Technical Debt, Group 1

#136 Fix: Group3 issues #37 #59 #60 #63 #64 #65 #112
  src/main/java/de/dennisguse/opentracks/TrackListActivity.java
  src/main/java/de/dennisguse/opentracks/data/ContentProviderUtils.java
  src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java
  src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
Labels: Group 3

#43 Remove unused method parameter 'context'.
  src/main/java/de/dennisguse/opentracks/fragments/ChooseActivityTypeDialogFragment.java
  src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
  src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
Labels: Technical Debt, Group 6

#133 fix: removed the unneessay TAG variable
  src/main/java/de/dennisguse/opentracks/io/file/importer/ImportActivity.java
Labels: Group 7
